/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ApiParseRouteImport } from './routes/api/parse'
import { Route as ApiDemoSchemaGenRouteImport } from './routes/api/demo-schema-gen'
import { Route as ApiDemoParseRouteImport } from './routes/api/demo-parse'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiParseRoute = ApiParseRouteImport.update({
  id: '/api/parse',
  path: '/api/parse',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiDemoSchemaGenRoute = ApiDemoSchemaGenRouteImport.update({
  id: '/api/demo-schema-gen',
  path: '/api/demo-schema-gen',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiDemoParseRoute = ApiDemoParseRouteImport.update({
  id: '/api/demo-parse',
  path: '/api/demo-parse',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/api/demo-parse': typeof ApiDemoParseRoute
  '/api/demo-schema-gen': typeof ApiDemoSchemaGenRoute
  '/api/parse': typeof ApiParseRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/api/demo-parse': typeof ApiDemoParseRoute
  '/api/demo-schema-gen': typeof ApiDemoSchemaGenRoute
  '/api/parse': typeof ApiParseRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/api/demo-parse': typeof ApiDemoParseRoute
  '/api/demo-schema-gen': typeof ApiDemoSchemaGenRoute
  '/api/parse': typeof ApiParseRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/api/demo-parse' | '/api/demo-schema-gen' | '/api/parse'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/api/demo-parse' | '/api/demo-schema-gen' | '/api/parse'
  id:
    | '__root__'
    | '/'
    | '/api/demo-parse'
    | '/api/demo-schema-gen'
    | '/api/parse'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ApiDemoParseRoute: typeof ApiDemoParseRoute
  ApiDemoSchemaGenRoute: typeof ApiDemoSchemaGenRoute
  ApiParseRoute: typeof ApiParseRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/parse': {
      id: '/api/parse'
      path: '/api/parse'
      fullPath: '/api/parse'
      preLoaderRoute: typeof ApiParseRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/demo-schema-gen': {
      id: '/api/demo-schema-gen'
      path: '/api/demo-schema-gen'
      fullPath: '/api/demo-schema-gen'
      preLoaderRoute: typeof ApiDemoSchemaGenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/demo-parse': {
      id: '/api/demo-parse'
      path: '/api/demo-parse'
      fullPath: '/api/demo-parse'
      preLoaderRoute: typeof ApiDemoParseRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ApiDemoParseRoute: ApiDemoParseRoute,
  ApiDemoSchemaGenRoute: ApiDemoSchemaGenRoute,
  ApiParseRoute: ApiParseRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
